### Auth signin
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "goodmorning@yahoo.com",
    "password": "2536helloWE"
}

### Auth signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "bye@yahoo.com",
    "password": "2536helloWE"
}

### Reports
POST http://localhost:3000/reports
content-type: application/json

{
    "make": "ikco",
    "model":"Dena plus",
    "year":2021,
    "price": 550000,
    "mileage": 1000,
    "lat": 0,
    "lng": 0
}


### approve Reports
PATCH http://localhost:3000/reports/5
content-type: application/json

{
    "approved": true
}


### get Reports for a car
GET http://localhost:3000/reports?make=ikco&model=runna plus&year=2022&lat=0&lng=0&mileage=17000
content-type: application/json

{
}